language: node_js
node_js:
  - "14"

install:
  - npm install
  - npx lerna bootstrap

jobs:
  include:
    - name: "Unit Tests"
      stage: "test: before build"
      script: npm test -- -- -- --coverage
      after_script:
        - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
    - name: "Lint"
      stage: "test: before build"
      script: npm run lint
    - name: "Build"
      stage: "build"
      script: npm run build
    - name: "Check es versions"
      stage: "test: after build"
      script: npm run test:es:version
    - if: tag =~ ^v # Run only for tags
      stage: "deploy"
      script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        - npm run release:publish
      skip_cleanup: true